version: "3"
services:

### Nginx container #########################################
  nginx:
    build:
      context: ./nginx/build
      args:
        IMAGE_BASE: $NGINX_IMAGE_BASE
        IMAGE_VERSION: $NGINX_IMAGE_VERSION
        IMAGE_TAG: $NGINX_IMAGE_TAG
        USER_GROUP: $GLOBAL_USER_GROUP
        USER_NAME: $GLOBAL_USER_NAME
        USER_GROUP_ID: $GLOBAL_USER_GROUP_ID
        USER_NAME_ID: $GLOBAL_USER_NAME_ID
        WORKING_DIR: $GLOBAL_WORKING_DIR
        TIME_ZONE: $GLOBAL_TIME_ZONE
        CDN_URl: $GLOBAL_CDN_URl
        BUILD_DEPS: $NGINX_BUILD_DEPS
        SAVE_DEPS: $NGINX_SAVE_DEPS
#    image: $NGINX_IMAGE_BASE:$NGINX_IMAGE_VERSION$NGINX_IMAGE_TAG
    container_name: $NGINX_CONTAINER_NAME
#    user: $GLOBAL_USER_NAME
    working_dir: $GLOBAL_WORKING_DIR
    depends_on:
      - radius
      - mysql
      - php
      - redis
    ports:
      - $NGINX_HTTP_PORT
      - $NGINX_HTTP_PORT_PORTAL
      - $NGINX_HTTPS_PORT
      - $NGINX_HTTP_PORT_ADMIN
    tmpfs:
      - $GLOBAL_WORKING_DIR
    volumes:
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - $SOURCE_SHARE_DIR/wwwroot:$GLOBAL_WORKING_DIR/wwwroot:ro
      - $SOURCE_SHARE_DIR/wwwlogs/nginx:$GLOBAL_WORKING_DIR/wwwlogs/nginx:rw
      - /usr/share/zoneinfo/$GLOBAL_TIME_ZONE:/usr/share/zoneinfo/$GLOBAL_TIME_ZONE:ro
    environment:
      TZ: $GLOBAL_TIME_ZONE
#    privileged: true
    restart: always
    stdin_open: true
    networks:
      - $GLOBAL_NETWORKS_NAME

  ### PHP container #########################################

  php:
    build:
      context: ./php/build
      args:
        IMAGE_BASE: $PHP_IMAGE_BASE
        IMAGE_VERSION: $PHP_IMAGE_VERSION
        IMAGE_TAG: $PHP_IMAGE_TAG
        USER_GROUP: $GLOBAL_USER_GROUP
        USER_NAME: $GLOBAL_USER_NAME
        USER_GROUP_ID: $GLOBAL_USER_GROUP_ID
        USER_NAME_ID: $GLOBAL_USER_NAME_ID
        WORKING_DIR: $GLOBAL_WORKING_DIR
        TIME_ZONE: $GLOBAL_TIME_ZONE
        CDN_URl: $GLOBAL_CDN_URl
        BUILD_DEPS: $PHP_BUILD_DEPS
        SAVE_DEPS: $PHP_SAVE_DEPS
        PECL_DEPS: $PHP_PECL_DEPS
    container_name: $PHP_CONTAINER_NAME
#    user: $GLOBAL_USER_NAME
    working_dir: $GLOBAL_WORKING_DIR
    ports:
      - $PHP_HTTP_PORT
    expose:
      - 9000
    tmpfs:
      - $GLOBAL_WORKING_DIR
    volumes:
      - ./php/conf://usr/local/etc/php/conf:ro
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./php/conf/php-fpm.d:/usr/local/etc/php-fpm.d/:ro
      - $SOURCE_SHARE_DIR/wwwroot:$GLOBAL_WORKING_DIR/wwwroot:ro
      - $SOURCE_SHARE_DIR/wwwlogs/php:$GLOBAL_WORKING_DIR/wwwlogs/php:rw
      - /usr/share/zoneinfo/$GLOBAL_TIME_ZONE:/usr/share/zoneinfo/$GLOBAL_TIME_ZONE:ro
    environment:
      TZ: $GLOBAL_TIME_ZONE
    privileged: true
    restart: always
    stdin_open: true
    networks:
      - $GLOBAL_NETWORKS_NAME

  ### Mysql container #########################################
  mysql:
    build:
      context: ./mysql/build
      args:
        IMAGE_BASE: $MYSQL_IMAGE_BASE
        IMAGE_VERSION: $MYSQL_IMAGE_VERSION
        IMAGE_TAG: $MYSQL_IMAGE_TAG
        USER_GROUP: $GLOBAL_USER_GROUP
        USER_NAME: $GLOBAL_USER_NAME
        USER_GROUP_ID: $GLOBAL_USER_GROUP_ID
        USER_NAME_ID: $GLOBAL_USER_NAME_ID
        WORKING_DIR: $GLOBAL_WORKING_DIR
        TIME_ZONE: $GLOBAL_TIME_ZONE
        CDN_URl: $GLOBAL_CDN_URl
        BUILD_DEPS: $MYSQL_BUILD_DEPS
        SAVE_DEPS: $MYSQL_SAVE_DEPS
#    image: $MYSQL_IMAGE_BASE:$MYSQL_IMAGE_VERSION$MYSQL_IMAGE_TAG
    container_name: $MYSQL_CONTAINER_NAME
#    user: $GLOBAL_USER_NAME
    working_dir: $GLOBAL_WORKING_DIR
    ports:
      - $MYSQL_HTTP_PORT
    expose:
      - 3306
    tmpfs:
      - $GLOBAL_WORKING_DIR
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf:ro
      - ../database/mysql:$GLOBAL_WORKING_DIR/database/mysql:rw
      - $SOURCE_SHARE_DIR/wwwlogs/mysql:$GLOBAL_WORKING_DIR/wwwlogs/mysql:rw
      - /usr/share/zoneinfo/$GLOBAL_TIME_ZONE:/usr/share/zoneinfo/$GLOBAL_TIME_ZONE:ro
    environment:
      TZ: $GLOBAL_TIME_ZONE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
#    privileged: true
    restart: always
    stdin_open: true
    networks:
      - $GLOBAL_NETWORKS_NAME

  ### Redis container #########################################
  redis:
    build:
      context: ./redis/build
      args:
        IMAGE_BASE: $REDIS_IMAGE_BASE
        IMAGE_VERSION: $REDIS_IMAGE_VERSION
        IMAGE_TAG: $REDIS_IMAGE_TAG
        USER_GROUP: $GLOBAL_USER_GROUP
        USER_NAME: $GLOBAL_USER_NAME
        USER_GROUP_ID: $GLOBAL_USER_GROUP_ID
        USER_NAME_ID: $GLOBAL_USER_NAME_ID
        WORKING_DIR: $GLOBAL_WORKING_DIR
        TIME_ZONE: $GLOBAL_TIME_ZONE
        CDN_URl: $GLOBAL_CDN_URl
        BUILD_DEPS: $REDIS_BUILD_DEPS
        SAVE_DEPS: $REDIS_SAVE_DEPS
#    image: $REDIS_IMAGE_BASE:$REDIS_IMAGE_VERSION$REDIS_IMAGE_TAG
    container_name: $REDIS_CONTAINER_NAME
#    user: $GLOBAL_USER_NAME
    working_dir: $GLOBAL_WORKING_DIR
    ports:
      - $REDIS_HTTP_PORT
    expose:
      - 6379
    tmpfs:
      - $GLOBAL_WORKING_DIR
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ../database/redis:$GLOBAL_WORKING_DIR/database/redis:rw
      - $SOURCE_SHARE_DIR/wwwlogs/redis:$GLOBAL_WORKING_DIR/wwwlogs/redis:rw
      - /usr/share/zoneinfo/$GLOBAL_TIME_ZONE:/usr/share/zoneinfo/$GLOBAL_TIME_ZONE:ro
    command:
      - sh
      - -ceux
      - |
        echo 1 > /proc/sys/vm/overcommit_memory ; \
        mkdir -p /sys/kernel/mm/transparent_hugepage ; \
        echo never > /sys/kernel/mm/transparent_hugepage/enabled ; \
        redis-server /usr/local/etc/redis/redis.conf ; \
        tail -f ;
#    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      TZ: $GLOBAL_TIME_ZONE
    privileged: true
    restart: always
    stdin_open: true
    networks:
      - $GLOBAL_NETWORKS_NAME

  ### Radius container #########################################
  radius:
    build:
      context: ./radius/build
      args:
        IMAGE_BASE: $RADIUS_IMAGE_BASE
        IMAGE_VERSION: $RADIUS_IMAGE_VERSION
        IMAGE_TAG: $RADIUS_IMAGE_TAG
        USER_GROUP: $GLOBAL_USER_GROUP
        USER_NAME: $GLOBAL_USER_NAME
        USER_GROUP_ID: $GLOBAL_USER_GROUP_ID
        USER_NAME_ID: $GLOBAL_USER_NAME_ID
        WORKING_DIR: $GLOBAL_WORKING_DIR
        TIME_ZONE: $GLOBAL_TIME_ZONE
        CDN_URl: $GLOBAL_CDN_URl
        BUILD_DEPS: $RADIUS_BUILD_DEPS
        SAVE_DEPS: $RADIUS_SAVE_DEPS
#    image: $RADIUS_IMAGE_BASE:$RADIUS_IMAGE_VERSION$RADIUS_IMAGE_TAG
    container_name: $RADIUS_CONTAINER_NAME
#    user: $GLOBAL_USER_NAME
    working_dir: $GLOBAL_WORKING_DIR
    ports:
      - $RADIUS_HTTP_PORT
    expose:
      - '1812/udp'
      - '1813/udp'
    tmpfs:
      - $GLOBAL_WORKING_DIR
    volumes:
      - $SOURCE_SHARE_DIR/wwwlogs/radius:$GLOBAL_WORKING_DIR/wwwlogs/radius:rw
      - /usr/share/zoneinfo/$GLOBAL_TIME_ZONE:/usr/share/zoneinfo/$GLOBAL_TIME_ZONE:ro
    environment:
      TZ: $GLOBAL_TIME_ZONE
#    privileged: true
    restart: always
    stdin_open: true
    networks:
      - $GLOBAL_NETWORKS_NAME

  ### Feeradius container #########################################
  freeradius:
    build:
      context: freeradius/build
      args:
        IMAGE_BASE: $RADIUS_IMAGE_BASE
        IMAGE_VERSION: $RADIUS_IMAGE_VERSION
        IMAGE_TAG: $RADIUS_IMAGE_TAG
        USER_GROUP: $GLOBAL_USER_GROUP
        USER_NAME: $GLOBAL_USER_NAME
        USER_GROUP_ID: $GLOBAL_USER_GROUP_ID
        USER_NAME_ID: $GLOBAL_USER_NAME_ID
        WORKING_DIR: $GLOBAL_WORKING_DIR
        TIME_ZONE: $GLOBAL_TIME_ZONE
        CDN_URl: $GLOBAL_CDN_URl
        BUILD_DEPS: $RADIUS_BUILD_DEPS
        SAVE_DEPS: $RADIUS_SAVE_DEPS
    container_name: dmp_freeradius
    #    user: $GLOBAL_USER_NAME
    working_dir: $GLOBAL_WORKING_DIR
    ports:
      - $RADIUS_HTTP_PORT
    expose:
      - '1812/udp'
      - '1813/udp'
      - '1814/udp'
    tmpfs:
      - $GLOBAL_WORKING_DIR
    volumes:
      - $SOURCE_SHARE_DIR/wwwlogs/radius:$GLOBAL_WORKING_DIR/wwwlogs/radius:rw
      - /usr/share/zoneinfo/$GLOBAL_TIME_ZONE:/usr/share/zoneinfo/$GLOBAL_TIME_ZONE:ro
    environment:
      TZ: $GLOBAL_TIME_ZONE
    privileged: true
    restart: always
    stdin_open: true
    networks:
      - $GLOBAL_NETWORKS_NAME

### Networks #########################################

networks:
  dnmp-networks:
    driver: bridge
  dnmp-nat:
    driver: $GLOBAL_NETWORKS_DRIVER
  dnmp-bridge:
    driver: $GLOBAL_NETWORKS_DRIVER
  dnmp-host:
    driver: $GLOBAL_NETWORKS_DRIVER
  dnmp-overlay:
    driver: $GLOBAL_NETWORKS_DRIVER
  dnmp-macvlan:
    driver: $GLOBAL_NETWORKS_DRIVER

